platform: config0-hub:::devops-solutions::platform-eval-config0
stacks:
  add_iac_ci:
    stack_alias: add_iac_ci
    arguments:
      repo_name: iac_ci
      subdir: asg
      branch: asg
      check_keyword: tf
      apply_keyword: tf
      destroy_keyword: tf
