stacks:
  eks:
    stack: config0-hub:::aws_eks2
    arguments:
      aws_default_region: us-east-1
      vpc_name: config0-iac
      eks_cluster: config0-eks
      general_external_dns_role_name: external-dns-yofool
      domain_filters: yofool.com,yofool.local
    connections:
      - reference: dev1
