global:
   platform: config0-publish:::platform-do
   metadata:   
     matchSelectors:
        vpc_info:
          match_base: aws_base_network
          match_params:
            must_exists: True
            resource_type: vpc
custom:
   vars_set:
     platform:
        stack_ref: vars_set 
     arguments: 
       vars_set_name: config0-eval-network
       evaluate: False
       arguments_hash:
         vpc_name: selector:::vpc_info::name
         vpc_id: selector:::vpc_info::vpc_id
         ami_filter: Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
         ami_owner: 099720109477 
     spec:
       serialization:
         to_base64:
           arguments:
             - labels_hash
             - arguments_hash
     metadata:
       matchSelectors:
         - vpc_info
